title: "開源指南"
description: "學習如何發起、經營一項開源專案。"

locale: zh-TW
translations:
  - locale: zh-TW
    name: 正體中文 (zh-TW)
    repository: github/open-source-guide

exclude:
  - bin
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - docs
  - Gemfile*
  - node_modules
  - package.json
  - Rakefile
  - README.md
  - script
  - test
  - vendor
  - node_modules

permalink: /:path/

collections:
  articles:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/cards/default.png
  - scope:
      path: ""
      type: articles
    values:
      layout: article

gems:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin

markdown: kramdown

sass:
  style: :compressed
  sass_dir: assets/css/
  load_paths:
    - node_modules

branch: gh-pages

github:
  repository_nwo: github/opensource.guide

twitter:
  username: github

facebook:
  publisher: https://www.facebook.com/GitHub/

theme: jekyll-theme-tactile