title: "오픈소스 가이드"
description: "프로젝트를 시작하고 성장시키는 방법에 대해 알아보십시오."

# See: docs/translations.md
locale: ko-KR
translations:
  en-US:
    name: English (US)
    url: https://opensource.guide

  ko-KR:  
    name: Korean
    url: https://kr.opensource.guide

exclude:
  - bin
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - docs
  - Gemfile*
  - node_modules
  - package.json
  - Rakefile
  - README.md
  - script
  - test
  - vendor
  - node_modules

permalink: /:path/

collections:
  articles:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/cards/default.png
  - scope:
      path: ""
      type: articles
    values:
      layout: article

gems:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

sass:
  style: :compressed
  sass_dir: assets/css/
  load_paths:
    - node_modules

branch: gh-pages

github:
  repository_nwo: github/opensource.guide

twitter:
  username: github

facebook:
  publisher: https://www.facebook.com/GitHub/
