baseurl: "/open-source-handbook"

exclude:
  - docs
  - Gemfile*
  - Rakefile
  - README.md
  - script
  - test

collections:
  content:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "content"
    values:
      layout: article
