baseurl: "/open-source-handbook"

exclude:
  - docs
  - Gemfile*
  - Rakefile
  - README.md
  - script
  - test

permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      layout: article
