name: Mark stale issues
on:
  workflow_dispatch:
  schedule:
  - cron: "0 12 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        stale-issue-message: >
          This issue has been automatically marked as stale because it has not
          had recent activity. It will be closed if no further activity occurs.
          Thank you for your contributions.
        stale-issue-label: "stale"
        exempt-issue-labels: "pinned,security,translation"
        days-before-issue-stale: 60
        days-before-issue-close: 7
        ascending: true
        operations-per-run: 100
